import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import DashboardHader from "@/components/dashboard/dashboardHeader";
import DashboardSideBar from "@/components/dashboard/dashboardSideBar";
import { AuthProvider } from "@/lib/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  mb-10 lg:mb-0`}
      >
        <AuthProvider>
          <main className="mx-auto flex ">
            <div className="p-6 h-[90vh] overflow-y-scroll flex-1">
              {children}
            </div>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
